### ISSUE TITLE
Exception thrown

### ISSUE THREAD

**Issue by KeithHartle** [jsreport/jsreport-dotnet-example-consoleapp#6]
Out of the box this is the error that the project throws when I try to run it. No changes or modifications to ht e project. This is the first time I tried to run it.

jsreport.Binary (2.9.0)
jsreport.Local (2.2.3)
jsreport.Tpes (2.7.0)

Errors on this line
            var invoiceReport = rs.RenderByNameAsync("Invoice", InvoiceData).Result;

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Error rendering report: instance has been daemonized and initialized successfully (pid: 5440)rendering has finished with errors:A critical error occurred while trying to execute the render command (2). Error while executing request to remote server. connect ETIMEDOUT 192.168.72.74:5488 (1). caused by error (2):-> stackError:    at onCriticalError (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:302:19)    at D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:256:14    at processTicksAndRejections (internal/process/task_queues.js:97:5)caused by error (1):-> meta = {"config":{"url":"http://localhost:5488/api/report","method":"post","data":"{\"$id\":\"1\",\"template\":{\"$id\":\"2\",\"name\":\"Invoice\"},\"options\":{\"$id\":\"3\",\"debug\":{\"$id\":\"4\",\"logsToResponseHeader\":true}},\"data\":{\"$id\":\"5\",\"number\":\"123\",\"seller\":{\"$id\":\"6\",\"name\":\"Next Step Webs, Inc.\",\"road\":\"12345 Sunny Road\",\"country\":\"Sunnyville, TX 12345\"},\"buyer\":{\"$id\":\"7\",\"name\":\"Acme Corp.\",\"road\":\"16 Johnson Road\",\"country\":\"Paris, France 8060\"},\"items\":[{\"$id\":\"8\",\"name\":\"Website design\",\"price\":300}]}}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/0.19.2","Content-Length":419},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"stream","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"httpsAgent":{"_events":{},"_eventsCount":2,"defaultPort":443,"protocol":"https:","options":{"rejectUnauthorized":false,"path":null},"requests":{},"sockets":{},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":false,"maxSockets":null,"maxFreeSockets":256,"maxCachedSessions":100,"_sessionCache":{"map":{},"list":[]}}},"code":"ETIMEDOUT"}-> stackError: Error while executing request to remote server    at Client.render (D:\snapshot\jsreport\node_modules\jsreport-client\lib\client.js)    at processTicksAndRejections (internal/process/task_queues.js:97:5)Request Error stack: Error: connect ETIMEDOUT 192.168.72.74:5488    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16))
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ConsoleApp.Program.Main(String[] args) in \\vmware-host\Shared Folders\Downloads\jsreport-dotnet-example-consoleapp-master\Program.cs:line 25

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
JsReportBinaryException: Error rendering report: instance has been daemonized and initialized successfully (pid: 5440)rendering has finished with errors:A critical error occurred while trying to execute the render command (2). Error while executing request to remote server. connect ETIMEDOUT 192.168.72.74:5488 (1). caused by error (2):-> stackError:    at onCriticalError (D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:302:19)    at D:\snapshot\jsreport\node_modules\jsreport-cli\lib\commands\render.js:256:14    at processTicksAndRejections (internal/process/task_queues.js:97:5)caused by error (1):-> meta = {"config":{"url":"http://localhost:5488/api/report","method":"post","data":"{\"$id\":\"1\",\"template\":{\"$id\":\"2\",\"name\":\"Invoice\"},\"options\":{\"$id\":\"3\",\"debug\":{\"$id\":\"4\",\"logsToResponseHeader\":true}},\"data\":{\"$id\":\"5\",\"number\":\"123\",\"seller\":{\"$id\":\"6\",\"name\":\"Next Step Webs, Inc.\",\"road\":\"12345 Sunny Road\",\"country\":\"Sunnyville, TX 12345\"},\"buyer\":{\"$id\":\"7\",\"name\":\"Acme Corp.\",\"road\":\"16 Johnson Road\",\"country\":\"Paris, France 8060\"},\"items\":[{\"$id\":\"8\",\"name\":\"Website design\",\"price\":300}]}}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/0.19.2","Content-Length":419},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"stream","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"httpsAgent":{"_events":{},"_eventsCount":2,"defaultPort":443,"protocol":"https:","options":{"rejectUnauthorized":false,"path":null},"requests":{},"sockets":{},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":false,"maxSockets":null,"maxFreeSockets":256,"maxCachedSessions":100,"_sessionCache":{"map":{},"list":[]}}},"code":"ETIMEDOUT"}-> stackError: Error while executing request to remote server    at Client.render (D:\snapshot\jsreport\node_modules\jsreport-client\lib\client.js)    at processTicksAndRejections (internal/process/task_queues.js:97:5)Request Error stack: Error: connect ETIMEDOUT 192.168.72.74:5488    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)

Going to http://localhost:5488 I can see the service running and can render the Invoice

**Comment by pofider** [comment]
The only thing that comes to my mind is that you use a proxy?
